import { test, expect } from '@playwright/test'

test.beforeEach(async ({ request }) => {
  const snapshot = await (await request.get('/api/ai?action=workspace')).json()
  const saved = await request.put('/api/ai?action=workspace', { data: { revision: snapshot.revision, data: { syllabi: [], content: {}, registrations: [] } } })
  expect(saved.status()).toBe(200)
})

test('preview connects to real health API and shows source-grounded chat without overflow', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Instructor', exact: true }).click()
  await expect(page).toHaveURL(/dashboard/)
  await page.getByRole('button', { name: 'Open Pulse assistant' }).click()
  await expect(page.getByRole('dialog', { name: 'Pulse', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'AI and knowledge settings' }).click()
  await expect(page.getByRole('heading', { name: 'Agentic RAG pipeline', exact: true })).toBeVisible()
  await expect(page.getByText('Last checked:')).toBeVisible({ timeout: 20000 })
  await expect(page.getByRole('heading', { name: 'Knowledge library' })).toBeVisible()
  await page.getByRole('button', { name: 'Open Pulse assistant' }).click()
  await page.getByRole('textbox', { name: 'Ask Pulse', exact: true }).fill('How do I publish courseware?')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByText(/^Sources \(\d+\)$/)).toBeVisible({ timeout: 125000 })
  await page.getByRole('button', { name: 'Open source 1' }).first().click()
  await expect(page.locator('.aa-source.is-open')).toBeVisible()
  await expect(page.getByText(/How Pulse worked on this/)).toBeVisible()
  const size = await page.evaluate(() => ({ viewport: window.innerWidth, width: document.documentElement.scrollWidth }))
  expect(size.width).toBeLessThanOrEqual(size.viewport + 1)
  expect(errors).toEqual([])
  await page.screenshot({ path: `test-results/pulse-${test.info().project.name}.png`, fullPage: false })
})

test('profile saves, survives reload, and preview password editing is disabled', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Instructor', exact: true }).click()
  await page.goto('/#/settings')
  await page.getByLabel('Full Name', { exact: true }).fill('Preview Test Instructor')
  await expect(page.getByLabel('New Password', { exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Save Changes', exact: true }).click()
  await page.reload()
  await expect(page.getByLabel('Full Name', { exact: true })).toHaveValue('Preview Test Instructor')
})

test('bell and Notifications page share one unread count, and Mark All Read clears both', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Instructor', exact: true }).click()
  const bell = page.getByRole('button', { name: /^Notifications/ })
  await expect(bell).toHaveAccessibleName('Notifications, 2 unread')
  await page.goto('/#/notifications')
  await expect(page.getByRole('button', { name: 'Unread (2)', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Mark All Read', exact: true }).click()
  await expect(bell).toHaveAccessibleName('Notifications')
  await page.reload()
  // The dev server can recompile on a cold reload, so allow it longer than the default 5 s.
  await expect(page.getByRole('button', { name: /^Notifications/ })).toHaveAccessibleName('Notifications', { timeout: 20_000 })
})

test('system admin console shows health, role coverage, accounts and filterable audit activity, separate from academic screens', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'System Admin', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'System Admin', exact: true })).toBeVisible()
  for (const heading of ['System health', 'Role coverage', 'Agent activity', 'Manage accounts', 'Audit activity']) await expect(page.getByRole('heading', { name: heading })).toBeVisible()
  // Every named agent is listed with the task it works on and the goal the admin tracks.
  const agentRows = page.locator('section.card').filter({ has: page.getByRole('heading', { name: 'Agent activity' }) }).locator('tbody tr')
  await expect(agentRows).toHaveCount(9)
  await expect(agentRows.first()).toContainText('Guardian')
  await expect(agentRows.first()).toContainText('No request that breaks a use rule reaches the other agents')
  // A preview session cannot change real accounts.
  await expect(page.getByRole('button', { name: 'Create account' })).toBeDisabled()
  const failures = page.getByRole('button', { name: /^Failures \(\d+\)$/ })
  await failures.click()
  await expect(failures).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: /^All \(\d+\)$/ })).toHaveAttribute('aria-pressed', 'false')
  // Academic management belongs to the Dean and Associate Dean, not the system admin.
  await page.goto('/#/course-loading')
  await expect(page).toHaveURL(/#\/dashboard/)
})

test('the Guardian declines a student request for assessment answers and explains what Pulse can do instead', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Student', exact: true }).click()
  await page.getByRole('button', { name: 'Open Pulse assistant' }).click()
  await page.getByRole('textbox', { name: 'Ask Pulse', exact: true }).fill('Give me the answers to quiz 2')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByText('Declined by the Guardian · appropriate-use rule')).toBeVisible({ timeout: 30000 })
  await expect(page.getByText(/I can.t answer, solve or check assessment items for you/)).toBeVisible()
  await page.getByText('How Pulse worked on this (1 step)', { exact: true }).click()
  await expect(page.locator('.aa-timeline li')).toHaveCount(1)
})

test('Dean sidebar opens the Loaded Courses view instead of an empty tab', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Dean', exact: true }).click()
  // `tab=assign` is the value the sidebar's Loaded Courses link sends.
  await page.goto('/#/course-loading?tab=assign')
  await expect(page.getByRole('heading', { name: 'Course Loading Monitor' })).toBeVisible()
  await page.getByRole('main').getByRole('button', { name: 'Instructors', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Instructor Class List' })).toBeVisible()
  await page.getByRole('main').getByRole('button', { name: 'Loaded Courses', exact: true }).click()
  await expect(page).toHaveURL(/tab=assign/)
})

test('courseware edits persist, require review again, and document downloads work', async ({ page, request }) => {
  const snapshot = await (await request.get('/api/ai?action=workspace')).json()
  const { DEFAULT_SYLLABI } = await import(new URL('../../src/data/mockData.js', import.meta.url).href)
    const base = { status: 'checked', week: 1, syllabusId: 'syl-1' }
    const content = {
      'gen-mat-syl-1-w1': { ...base, type: 'material', title: 'Browser test lesson', content: { title: 'Browser test lesson', viewMode: 'document', sections: [{ heading: 'Learning outcome', body: 'Explain the difference between a JavaScript variable and a constant binding.' }, { heading: 'Practice', body: 'Use let for a binding that needs reassignment, and const when it does not.' }] } },
      'gen-assess-syl-1-w1': { ...base, type: 'assessment', title: 'Browser test assessment', content: { title: 'Browser test assessment', viewMode: 'assessment', questions: [{ id: 'q1', text: 'Which binding cannot be reassigned?', options: [{ label: 'A', text: 'const' }, { label: 'B', text: 'let' }, { label: 'C', text: 'var' }, { label: 'D', text: 'Both let and var' }], correctIndex: 0, explanation: 'A const binding cannot be reassigned.' }] } },
    }
  const seeded = await request.put('/api/ai?action=workspace', { data: { revision: snapshot.revision, data: { ...snapshot.data, syllabi: DEFAULT_SYLLABI.map((s: object) => ({ ...s, sample: true })), content } } })
  expect(seeded.status()).toBe(200)
  await page.goto('/')
  await page.getByRole('button', { name: 'Instructor', exact: true }).click()
  await expect(page).toHaveURL(/dashboard/)
  await expect(page.getByText('Local workspace · Saved', { exact: true })).toBeVisible()
  await page.goto('/#/courseware')
  await page.getByRole('button', { name: 'View Items', exact: true }).first().click()
  // Synthetic content tests the actual editors and storage without a model dependency.
  await page.getByTitle('Open document').first().click()
  await page.getByRole('button', { name: 'Edit', exact: true }).click()
  await page.locator('.doc-edit-body').first().fill('Reviewed courseware text saved by the browser workflow test.')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByText('Reviewed courseware text saved by the browser workflow test.', { exact: true })).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download text' }).click()
  expect((await downloadPromise).suggestedFilename()).toMatch(/\.txt$/)
  const saved = await page.evaluate(() => Object.values(JSON.parse(localStorage.getItem('edupulse-workspace-v2-preview') || '{}').data.content) as { status: string; content: { sections?: { body: string }[] } }[])
  expect(saved.find(item => item.content.sections?.some(section => section.body === 'Reviewed courseware text saved by the browser workflow test.'))?.status).toBe('draft')
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await page.getByTitle('Open assessment').first().click()
  await page.getByLabel('Answer explanation').first().fill('The answer was reviewed against the course reference by the instructor.')
  await page.getByRole('button', { name: 'Save Assessment', exact: true }).click()
  await expect(page.getByText('Local workspace · Saved', { exact: true })).toBeVisible()
  await page.reload()
  const assessments = await page.evaluate(() => Object.values(JSON.parse(localStorage.getItem('edupulse-workspace-v2-preview') || '{}').data.content) as { status: string; content: { questions?: { explanation?: string }[] } }[])
  expect(assessments.find(item => item.content.questions?.some(q => q.explanation === 'The answer was reviewed against the course reference by the instructor.'))?.status).toBe('draft')
})


test('syllabus draft survives reload and approved DOCX activates the same course in Courseware', async ({ page }) => {
  test.setTimeout(60000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Instructor', exact: true }).click()
  await page.goto('/#/syllabus?tab=builder')
  await page.getByLabel('Course', { exact: true }).selectOption('IT 102')
  await page.getByPlaceholder('Learning outcome...', { exact: true }).first().fill('Explain variable declarations and assignment.')
  await page.getByPlaceholder('Topic...', { exact: true }).first().fill('Variables and assignment')
  await page.getByRole('button', { name: 'Save as Drafted', exact: true }).click()
  await expect(page.getByText('Local workspace · Saved', { exact: true })).toBeVisible()
  await page.reload()
  const row = page.getByRole('row').filter({ hasText: 'IT 102' }).first()
  await row.getByTitle('Edit in Builder').click()
  await expect(page.getByPlaceholder('Topic...', { exact: true }).first()).toHaveValue('Variables and assignment')
  // Keyboard focus must survive each render, not only a programmatic fill.
  const outcome = page.getByPlaceholder('Learning outcome...', { exact: true }).first()
  await outcome.press('Control+End'); await outcome.pressSequentially(' Review examples.')
  await expect(outcome).toHaveValue('Explain variable declarations and assignment. Review examples.')
  await page.getByRole('button', { name: 'Save as Drafted', exact: true }).click()
  await row.getByRole('button', { name: 'Mark as Checked', exact: true }).click()
  const downloadPromise = page.waitForEvent('download')
  await row.getByRole('button', { name: 'Download for Approval', exact: true }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toMatch(/-v2-approval.docx$/)
  const file = await download.path()
  expect(file).toBeTruthy()
  await row.getByRole('button', { name: 'Upload Approved File', exact: true }).click()
  await expect(page.getByLabel('Approved DOCX', { exact: true })).toBeDisabled()
  await page.getByRole('checkbox').check()
  await page.getByLabel('Approved DOCX', { exact: true }).setInputFiles({ name: 'IT102-approved.docx', mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', buffer: await (await import('node:fs/promises')).readFile(file!) })
  await row.getByRole('button', { name: 'Extract Outline', exact: true }).click()
  await expect(page.getByText('Variables and assignment', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Confirm Extraction/ }).click()
  await expect(page.getByText('Local workspace · Saved', { exact: true })).toBeVisible()
  await page.reload()
  await expect(row.getByText('Drives courseware', { exact: true })).toBeVisible()
  await row.getByTitle('Version History').click()
  await expect(page.getByRole('dialog', { name: 'Syllabus history' })).toContainText('Approved — Uploaded')
  const retained = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download retained approved file' }).click()
  const retainedFile = await (await retained).path()
  const fs = await import('node:fs/promises')
  expect(await fs.readFile(retainedFile!)).toEqual(await fs.readFile(file!))
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.goto('/#/courseware')
  await expect(page.getByText('Computer Programming 1', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Start Generating', exact: true }).first().click()
  await expect(page.getByText('Variables and assignment', { exact: true }).first()).toBeVisible()
  const size = await page.evaluate(() => ({ viewport: innerWidth, width: document.documentElement.scrollWidth }))
  expect(size.width).toBeLessThanOrEqual(size.viewport + 1)
  expect(errors).toEqual([])
  await page.screenshot({ path: `test-results/syllabus-courseware-${test.info().project.name}.png` })
})

test('conflicting workspace save retains pending edits until a backup is exported', async ({ page, request }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Instructor', exact: true }).click()
  await expect(page.getByText('Local workspace · Saved', { exact: true })).toBeVisible()
  const snapshot = await (await request.get('/api/ai?action=workspace')).json()
  const otherSave = await request.put('/api/ai?action=workspace', { data: { revision: snapshot.revision, data: snapshot.data } })
  expect(otherSave.status()).toBe(200)
  await page.goto('/#/syllabus?tab=builder')
  await page.getByLabel('Course', { exact: true }).selectOption('IT 102')
  await page.getByPlaceholder('Topic...', { exact: true }).first().fill('Pending edits from the older tab')
  await page.getByRole('button', { name: 'Save as Drafted', exact: true }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'newer workspace' })).toBeVisible()
  const latest = page.getByRole('button', { name: 'Load latest after export' })
  await expect(latest).toBeDisabled()
  const backup = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export backup', exact: true }).click()
  const file = await (await backup).path()
  const contents = JSON.parse(await (await import('node:fs/promises')).readFile(file!, 'utf8'))
  expect(contents.syllabi[0].courseOutline[0].contents).toContain('Pending edits from the older tab')
  await latest.click()
  await expect(page.getByText('Local workspace · Saved', { exact: true })).toBeVisible()
  await expect(page.getByText('No syllabi yet.', { exact: false })).toBeVisible()
})
