import { createContext, useContext, useState, useCallback } from 'react'

const translations = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.syllabus': 'Syllabus',
    'nav.courseware': 'Courseware',
    'nav.performance': 'Performance',
    'nav.settings': 'Settings',
    'nav.ai-assistant': 'AI Assistant',
    'nav.notifications': 'Notifications',
    'nav.help': 'Help & Support',
    'nav.import': 'Data Import',
    'nav.audit': 'Audit Log',
    'nav.ai-pipeline': 'AI Pipeline',
    'nav.edusuite': 'EduSuite',
    'nav.integrity': 'Academic Integrity',
    'nav.api-docs': 'API Docs',
    'nav.model-governance': 'Model Governance',
    'nav.operations': 'Operations',
    'nav.roadmap': 'Roadmap',
    'nav.content-editor': 'Content Editor',
    'nav.qa-dashboard': 'QA Dashboard',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.submit': 'Submit',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.loading': 'Loading...',
    'common.noData': 'No data available',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.run': 'Run',
    'common.view': 'View',
    'common.retry': 'Retry',
    'common.approve': 'Approve',
    'common.reject': 'Reject',
    'common.all': 'All',
    'common.status': 'Status',
    'common.type': 'Type',
    'common.priority': 'Priority',
    'common.actions': 'Actions',
    'common.date': 'Date',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.module': 'Module',
    'common.owner': 'Owner',
    'common.createdAt': 'Created At',
    'common.updatedAt': 'Updated At',
    'common.dueDate': 'Due Date',
    'common.passed': 'Passed',
    'common.failed': 'Failed',
    'common.queued': 'Queued',
    'common.inProgress': 'In Progress',
    'common.blocked': 'Blocked',
    'common.critical': 'Critical',
    'common.high': 'High',
    'common.medium': 'Medium',
    'common.low': 'Low',
    'common.overview': 'Overview',
    'common.details': 'Details',
    'common.history': 'History',
    'common.summary': 'Summary',
    'common.settings': 'Settings',
    'common.general': 'General',
    'common.advanced': 'Advanced',
    'common.account': 'Account',
    'common.appearance': 'Appearance',
    'common.notifications': 'Notifications',
    'common.users': 'Users',
    'common.integrations': 'Integrations',
    'common.features': 'Features',
    'dashboard.welcome': 'Welcome back',
    'dashboard.overview': 'Here\'s your overview for today',
    'dashboard.students': 'Students',
    'dashboard.instructors': 'Instructors',
    'dashboard.courses': 'Courses',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.upcomingTasks': 'Upcoming Tasks',
    'dashboard.systemHealth': 'System Health',
    'syllabus.upload': 'Upload Syllabus',
    'syllabus.generate': 'Generate from Curriculum',
    'syllabus.compliance': 'Compliance',
    'syllabus.versions': 'Versions',
    'courseware.generate': 'Generate Courseware',
    'courseware.review': 'Review',
    'courseware.publish': 'Publish',
    'courseware.bulkActions': 'Bulk Actions',
    'performance.heatmap': 'Heatmap',
    'performance.radar': 'Radar Chart',
    'performance.trends': 'Trends',
    'performance.students': 'Student Details',
    'aiAssistant.title': 'AI Assistant',
    'aiAssistant.placeholder': 'Ask anything about your syllabus or courseware...',
    'aiAssistant.sessions': 'Sessions',
    'login.title': 'EduPulse',
    'login.subtitle': 'AI-Driven Learning Management System',
    'login.selectRole': 'Select your role to continue',
    'login.dean': 'Dean',
    'login.instructor': 'Instructor',
    'login.student': 'Student',
    'login.continue': 'Continue',
    'error.notFound': 'Page Not Found',
    'error.serverError': 'Server Error',
    'error.goBack': 'Go back to Dashboard',
    'privacy.title': 'Privacy Policy',
    'terms.title': 'Terms of Use',
    'editor.title': 'Content Editor',
    'editor.metadata': 'Metadata',
    'editor.accessibility': 'Accessibility',
    'editor.provenance': 'Provenance',
    'editor.readability': 'Readability',
    'editor.citations': 'Citations',
    'editor.localization': 'Localization',
    'editor.comments': 'Reviewer Comments',
    'editor.aiGenerated': 'AI-Generated',
    'editor.humanAuthored': 'Human-Authored',
    'editor.autoSave': 'Auto-saved',
    'editor.lastSaved': 'Last saved',
    'qaDashboard.title': 'QA Dashboard',
    'qaDashboard.queue': 'Test Queue',
    'qaDashboard.coverage': 'Coverage',
    'qaDashboard.recentResults': 'Recent Results',
    'qaDashboard.regressions': 'Regressions',
    'qaDashboard.totalTests': 'Total Tests',
    'qaDashboard.avgCoverage': 'Avg Coverage',
  },
  fil: {
    'nav.dashboard': 'Dashboard',
    'nav.syllabus': 'Silab',
    'nav.courseware': 'Kurso',
    'nav.performance': 'Pagganap',
    'nav.settings': 'Mga Setting',
    'nav.ai-assistant': 'AI na Katulong',
    'nav.notifications': 'Mga Abiso',
    'nav.help': 'Tulong at Suporta',
    'nav.import': 'Pag-import ng Datos',
    'nav.audit': 'Talaan ng Audit',
    'nav.ai-pipeline': 'AI Pipeline',
    'nav.edusuite': 'EduSuite',
    'nav.integrity': 'Akademikong Integridad',
    'nav.api-docs': 'API Docs',
    'nav.model-governance': 'Pamamahala ng Modelo',
    'nav.operations': 'Mga Operasyon',
    'nav.roadmap': 'Roadmap',
    'nav.content-editor': 'Taga-edit ng Nilalaman',
    'nav.qa-dashboard': 'QA Dashboard',
    'common.save': 'I-save',
    'common.cancel': 'Kanselahin',
    'common.delete': 'Tanggalin',
    'common.edit': 'I-edit',
    'common.submit': 'Isumite',
    'common.close': 'Isara',
    'common.search': 'Hanapin',
    'common.filter': 'Salain',
    'common.export': 'I-export',
    'common.import': 'I-import',
    'common.loading': 'Naglo-load...',
    'common.noData': 'Walang datos',
    'common.confirm': 'Kumpirmahin',
    'common.back': 'Bumalik',
    'common.next': 'Susunod',
    'common.previous': 'Nakaraan',
    'common.run': 'Patakbuhin',
    'common.view': 'Tingnan',
    'common.retry': 'Subukan muli',
    'common.approve': 'Aprubahan',
    'common.reject': 'Tanggihan',
    'common.all': 'Lahat',
    'common.status': 'Katayuan',
    'common.type': 'Uri',
    'common.priority': 'Priyoridad',
    'common.actions': 'Mga Aksyon',
    'common.date': 'Petsa',
    'common.name': 'Pangalan',
    'common.description': 'Paglalarawan',
    'common.module': 'Modul',
    'common.owner': 'May-ari',
    'common.createdAt': 'Ginawa noong',
    'common.updatedAt': 'Na-update noong',
    'common.dueDate': 'Petsa ng Deadline',
    'common.passed': 'Nakapasa',
    'common.failed': 'Nabigo',
    'common.queued': 'Nasa Queue',
    'common.inProgress': 'Kasalukuyang Ginagawa',
    'common.blocked': 'Na-block',
    'common.critical': 'Kritikal',
    'common.high': 'Mataas',
    'common.medium': 'Katamtaman',
    'common.low': 'Mababa',
    'common.overview': 'Pangkalahatang-tanaw',
    'common.details': 'Mga Detalye',
    'common.history': 'Kasaysayan',
    'common.summary': 'Buod',
    'common.settings': 'Mga Setting',
    'common.general': 'Pangkalahatan',
    'common.advanced': 'Mas Advanced',
    'common.account': 'Account',
    'common.appearance': 'Hitsura',
    'common.notifications': 'Mga Abiso',
    'common.users': 'Mga Gumagamit',
    'common.integrations': 'Mga Integrasyon',
    'common.features': 'Mga Tampok',
    'dashboard.welcome': 'Maligayang pagbabalik',
    'dashboard.overview': 'Ito ang iyong pangkalahatang-tanaw ngayon',
    'dashboard.students': 'Mga Mag-aaral',
    'dashboard.instructors': 'Mga Tagapagturo',
    'dashboard.courses': 'Mga Kurso',
    'dashboard.recentActivity': 'Kamakailang Aktibidad',
    'dashboard.upcomingTasks': 'Mga Paparating na Gawain',
    'dashboard.systemHealth': 'Kalusugan ng Sistema',
    'syllabus.upload': 'I-upload ang Silab',
    'syllabus.generate': 'Bumasi sa Curriculm',
    'syllabus.compliance': 'Pagsunod',
    'syllabus.versions': 'Mga Bersyon',
    'courseware.generate': 'Bumuo ng Kurso',
    'courseware.review': 'Suriin',
    'courseware.publish': 'I-publish',
    'courseware.bulkActions': 'Mga Bulk Action',
    'performance.heatmap': 'Heatmap',
    'performance.radar': 'Radar Chart',
    'performance.trends': 'Mga Trend',
    'performance.students': 'Detalye ng Mag-aaral',
    'aiAssistant.title': 'AI na Katulong',
    'aiAssistant.placeholder': 'Magtanong tungkol sa iyong silab o kurso...',
    'aiAssistant.sessions': 'Mga Session',
    'login.title': 'EduPulse',
    'login.subtitle': 'AI-Driven Learning Management System',
    'login.selectRole': 'Pumili ng tungkulin upang magpatuloy',
    'login.dean': 'Dekano',
    'login.instructor': 'Tagapagturo',
    'login.student': 'Mag-aaral',
    'login.continue': 'Magpatuloy',
    'error.notFound': 'Hindi Nahanap',
    'error.serverError': 'Error sa Server',
    'error.goBack': 'Bumalik sa Dashboard',
    'privacy.title': 'Patakaran sa Privacy',
    'terms.title': 'Mga Tuntunin ng Paggamit',
    'editor.title': 'Taga-edit ng Nilalaman',
    'editor.metadata': 'Metadata',
    'editor.accessibility': 'Na-access',
    'editor.provenance': 'Pinagmulan',
    'editor.readability': 'Nababasa',
    'editor.citations': 'Mga Sipi',
    'editor.localization': 'Lokalisa',
    'editor.comments': 'Mga Komento',
    'editor.aiGenerated': 'Gawa sa AI',
    'editor.humanAuthored': 'Gawa sa Tao',
    'editor.autoSave': 'Auto-saved',
    'editor.lastSaved': 'Huling na-save',
    'qaDashboard.title': 'QA Dashboard',
    'qaDashboard.queue': 'Test Queue',
    'qaDashboard.coverage': 'Saklaw',
    'qaDashboard.recentResults': 'Kamakailang Resulta',
    'qaDashboard.regressions': 'Mga Regresyon',
    'qaDashboard.totalTests': 'Kabuuang Test',
    'qaDashboard.avgCoverage': 'Avg na Saklaw',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('edupulse-lang') || 'en')

  const switchLanguage = useCallback((lang) => {
    setLanguage(lang)
    localStorage.setItem('edupulse-lang', lang)
  }, [])

  const t = useCallback((key) => {
    return translations[language]?.[key] || translations.en[key] || key
  }, [language])

  return (
    <LanguageContext.Provider value={{ language, switchLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}
