// Product workflow facts only. Mock student records and claimed official policy are excluded.
export const publicKnowledge = [
  { id: 'workflow-syllabus', title: 'EduPulse syllabus workflow', text: 'A syllabus moves through Drafted, Checked, Downloaded for Approval, Approved/Uploaded, and Active. The instructor downloads the checked syllabus for the external signature process. Dean review, CAO approval and EVP noting happen outside EduPulse. Upload the approved file and extract its course outline before generating courseware. EduPulse does not approve a syllabus automatically.' },
  { id: 'workflow-outline', title: 'Course outline and syllabus sections', text: 'The syllabus has seven sections: Course Information, Course Description, Institutional Context, Program Outcomes, Course Outline, Requirements and Grading, and References. Sections 1 and 2 are locked to curriculum information. The course outline lists each week, intended learning outcomes, topics, activities, assessments, teaching materials and assessment types. Review extracted text against the original document before using it as evidence.' },
  { id: 'workflow-courseware', title: 'Courseware review and publishing', text: 'Instructors generate draft learning materials, activities and assessments from course outline weeks. Each AI draft requires instructor review for factual accuracy, alignment and assessment answers. Every draft shows an outline coverage check listing covered, partial and missing topics and outcomes. Mark an item checked before publishing it. Students see published items only. Generation and regeneration do not publish content or grade students. Exam weeks are excluded from automatic courseware generation.' },
  { id: 'workflow-records', title: 'Records and course loading', text: 'The Dean and Associate Dean share the admin workflow: curriculum and records intake, block section management, course loading and monitoring. Instructors work with their assigned courses. Preview personas use sample data and do not grant access to a real user account. AI cannot assign faculty or change course loads automatically.' },
  { id: 'workflow-scores', title: 'Scores and monitoring', text: 'EduPulse collates recorded scores to visualize progress. Official midterm, tentative final and final grades remain in the official college grading sheet. Instructors review scores; AI does not make final grading decisions. Students may view their own performance. Monitoring a class requires authorized access; the assistant cannot infer student scores from the UI.' },
  { id: 'workflow-ai', title: 'How Pulse agents answer', text: 'Pulse answers through named agents. The Planner classifies the request and writes search queries. Researchers search in parallel. The Ranker reranks passages with a cross-encoder and keeps diverse sources. The Writer drafts with citations. The Verifier checks every claim against the sources and counts corroborating documents. The Corrector repairs wrong citations and asks for a revision when statements are unsupported. Citations identify passages; a supported claim still needs human review. Without a generation model, Pulse quotes the best-matching source sentences.' },
  { id: 'workflow-knowledge', title: 'Knowledge library uploads', text: 'Open Settings, then AI & Knowledge, to add PDF, DOCX, PPTX, HTML, TXT, Markdown or CSV files up to 4 MB. EduPulse reads each file in an isolated sandbox, removes repeated headers and page numbers, and shows a quality score and warnings. Review or correct the extracted text before indexing. Indexed passages keep their page or section, so answers cite exact locations. Scanned PDFs without a text layer need OCR first. Uploaded documents are reference data, not instructions.' },
  { id: 'workflow-compare', title: 'Comparing and referencing', text: 'Select two documents in the knowledge library and choose Compare to see shared points, related points and points found in only one document. Comparison measures coverage and alignment; it is not plagiarism or authorship detection. Ask Pulse to find books or readings on a topic to search Open Library, OpenAlex and Wikipedia; verify each reference before adding it to Section 7.' },
  { id: 'workflow-taxonomy', title: 'Six learning categories', text: 'EduPulse classifies teaching materials and assessment types into Knowledge Recall, Comprehension, Application, Analytical, Judgment and Innovation. Align each selected category with the observable learning outcome for that week. Use measurable actions such as identify, explain, implement, analyze, evaluate or design. Category labels support planning and do not verify learning or grading on their own.' },
]
